language: python
python:
 - 2.6
 - 2.7
 - pypy
install:
 - python setup.py install
script:
 - python -m unittest discover test_replays
 - python -m unittest discover test_s2gs
notifications:
  irc: "chat.freenode.net#sc2reader"
