language: python
python:
 - 2.6
 - 2.7
 - pypy
install:
 - python setup.py install
script:
 - python test_replays/test_all.py
 - python test_s2gs/test_all.py
notifications:
  irc: "chat.freenode.net#sc2reader"
