language: python
python:
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - pypy
install:
 - python setup.py install
script:
 - python test_replays/test_all.py
 - python test_s2gs/test_all.py
branches:
  only:
    - master
notifications:
  irc: "chat.freenode.net#sc2reader"
